[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "plm4cpp-xai"
version = "0.1.0"
description = "Consensus explainable protein language model workflow for CPP prediction and interpretation"
requires-python = ">=3.12"
authors = [
  {name = "Nandan Kumar"},
  {name = "Yonghui Li"}
]

[tool.setuptools.packages.find]
where = ["src"]
